const colors = {
    dark: {
      text: "#FFFFFF",
      tint: "#F59E0B",
      background: "#0A0A0A",
      foreground: "#FFFFFF",
      card: "#141414",
      cardForeground: "#FFFFFF",
      primary: "#F59E0B",
      primaryForeground: "#000000",
      secondary: "#1C1C1C",
      secondaryForeground: "#FFFFFF",
      muted: "#1C1C1C",
      mutedForeground: "#6B7280",
      accent: "#FBBF24",
      accentForeground: "#000000",
      destructive: "#EF4444",
      destructiveForeground: "#FFFFFF",
      border: "#262626",
      input: "#1C1C1C",
    },
    light: {
      text: "#0A0A0A",
      tint: "#D97706",
      background: "#FFFFFF",
      foreground: "#0A0A0A",
      card: "#F9F9F9",
      cardForeground: "#0A0A0A",
      primary: "#D97706",
      primaryForeground: "#FFFFFF",
      secondary: "#F0F0F0",
      secondaryForeground: "#1A1A1A",
      muted: "#F0F0F0",
      mutedForeground: "#737373",
      accent: "#F59E0B",
      accentForeground: "#000000",
      destructive: "#EF4444",
      destructiveForeground: "#FFFFFF",
      border: "#E5E5E5",
      input: "#E5E5E5",
    },
    radius: 10,
  };
  export default colors;